kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-creators
subjects:
- kind: ServiceAccount
  name: default
  namespace: app1
roleRef:
  kind: Role
  name: deployment-creator
  apiGroup: rbac.authorization.k8s.io